# Generated by Django 4.2.6 on 2023-10-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Ha noi', 'Ha noi'), ('Tp HoChiMinh', 'Tp HoChiMinh'), ('Thanh Hoa', 'Thanh Hoa'), ('Nghe An', 'Nghe An'), ('Ha Tinh', 'Ha Tinh'), ('Quang Binh', 'Quang Binh'), ('Quang Tri', 'Quang Tri'), ('Quang Ngai', 'Quang Ngai'), ('Thua Thien Hue', 'Thua Thien Hue'), ('Da Nang', 'Da Nang'), ('Phu Yen', 'Phu Yen'), ('Nha Trang', 'Nha Trang'), ('Khanh Hoa', 'Khanh Hoa'), ('Vung Tau', 'Vung Tau'), ('Binh Duong', 'Binh Duong'), ('Dong Nai', 'Dong Nai')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
